logger:
  level: debug

yuemiao:
  tk: "wxtoken:a124fb15dede8e2eb066bd68793b9065_2ee27d6ac506ef6036e33f9972f0a9cc"

  province:
    name: "四川省"
    code: "51"
  city:
    name: "成都市"
    code: "5101"
