logger:
  level: debug

yuemiao:
  tk: "wxtoken:a124fb15dede8e2eb066bd68793b9065_9d5cc7e04c524d712cfbe9559fc4e542"

  province:
    name: "四川省"
    code: "51"
  city:
    name: "成都市"
    code: "5101"
