logger:
  level: debug

# 约苗平台
yuemiao:
  # 用爬虫工具获取header的TK值
  tk: "wxtoken:a124fb15dede8e2eb066bd68793b9065_18a4c61476e16628fdae1c36d1fc6f43"

region:
  - province:
    name: "四川省"
    code: 51

#    city:
#      name: "成都市"
#      code: 5101
