logger:
  level: debug

yuemiao:
  tk: "wxtoken:a124fb15dede8e2eb066bd68793b9065_6604d5a69efd1f5c96b7471919ca9647"

  province:
    name: "四川省"
    code: "51"
  city:
    name: "成都市"
    code: "5101"
