logger:
  level: debug

yuemiao:
  tk: "wxtoken:a124fb15dede8e2eb066bd68793b9065_bfdd37a6547b7c428d2af90b01567dcf"

  province:
    name: "四川省"
    code: "51"
  city:
    name: "成都市"
    code: "5101"
