logger:
  level: debug
  debug: false

yuemiao:
  tk: "wxtoken:a124fb15dede8e2eb066bd68793b9065_612863f96b9f88fe60d209d49f76124f"

  province:
    name: "四川省"
    code: "51"
  city:
    name: "成都市"
    code: "5101"
